title: Eduardo Ortega
logo: /assets/img/circle.png
description: Data Scientist | AnÃ¡lisis de Datos | ML
## ğŸ“ Enlaces y Contacto

- ğŸ“„ [CurrÃ­culum (Google Drive)](https://drive.google.com/file/d/1By1Y01hmr3DnA2UzcXPWbjPoqvpEkfKn/view?usp=sharing)
- ğŸ’¼ [LinkedIn](https://www.linkedin.com/in/eduardo-ortega-30154629a/)  
- ğŸ“§ lalox1697@gmail.com
show_downloads: true
theme: jekyll-theme-minimal
